sampling_frequency = 200

[data_path]
directory = "D:\\wave_craze software demo\\wave_craze"

[parameters]
lb = "float"
lm = "float"
mm = "float"
kk = "float"
p = "float"

[y_limit]
y1 = [ -2.0, 10.0,]
y2 = [ 1.0, 9.0,]
y3 = [ -2.0, 11.0,]
y4 = [ -1.0, 11.0,]
