sampling_frequency = 200

[data_path]
directory = "D:\\wave_craze software demo\\wave_craze"

[parameters]
"torque sensor" = "float"
encoder = "float"

[y_limit]
y1 = [ -2.0, 100.0,]
y2 = [ 1.0, 10.0,]
y3 = [ -2.0, 11.0,]
y4 = [ -1.0, 11.0,]
